spring:
  application:
    name: product-service
  mongodb:
    host: product-db
    port: 27017
    database: product_db
    username: chris
    password: chris
    authentication-database: admin
server:
  port: 8001